twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        siteName: '%app.site_name%'
        siteDescription: '%app.site_description%'
        siteAlert: '%app.site_alert%'

    # fix to look for translations in forms.
    # TODO: Remove when symfony is upgraded to 5.3
    paths:
        '%kernel.project_dir%/src/Form': ~
        '%kernel.project_dir%/src/Controller': ~
