twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        siteName: '%app.siteName%'
        siteDescription: '%app.siteDescription%'
        siteAlert: '%app.siteAlert%'

    # fix to look for translations in forms.
    # TODO: Remove when symfony is upgraded to 5.3
    paths:
        '%kernel.project_dir%/src/Form': ~
