twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        siteName: '%app.site_name%'
        siteDescription: '%app.site_description%'
        siteAlert: '%app.site_alert%'
        bootswatchTheme: '%app.bootswatch_theme%'
